function gravar_excel_estat(nome,tempo,velocidade,direcao,caminho,...
    range,gaps,rep,sinc,spike,inc,amb,excluidos,inclinacao)
velocidade(velocidade==999)=nan;direcao(direcao==999)=nan;
[u,v]=veldir2uv(velocidade,direcao);
num_cel=size(velocidade,2);

%máximo vetorial
[max_vet e]=nanmax(velocidade);
for i=1:num_cel
    pos_dir_vet(i,1)=direcao(e(i),i);
    pos_tempo_vet(i,1)=tempo(e(i),1);
end

%máximo u, máximo v, mínimo u, mínimo v
[max_u f]=nanmax(u);
for j=1:num_cel
pos_tempo_max_u(j,1)=tempo(f(j),1);
end

[max_v g]=nanmax(v);
for k=1:num_cel
pos_tempo_max_v(k,1)=tempo(g(k),1);
end

[min_u h]=nanmin(u);
for l=1:num_cel
pos_tempo_min_u(l,1)=tempo(h(l),1);
end

[min_v m]=nanmin(v);
for n=1:num_cel
pos_tempo_min_v(n,1)=tempo(m(n),1);
end

%média, mediana e desvio padrão
media_u=nanmean(u);media_v=nanmean(v);
mediana_u=nanmedian(u);mediana_v=nanmedian(v);
std_u=nanstd(u);std_v=nanstd(v);

media_vetorial=[];
for k=1:num_cel
    for kk=1:length(u)
    media_vetorial_aux(kk,k)=sqrt((u(kk,k)^2)+(v(kk,k)^2));
    end
    media_vetorial(1,k)=nanmean(media_vetorial_aux(:,k));
end

str_uv=repmat({'U(m/s)' 'V(m/s)'},1,num_cel);

cont=[];
for i=1:num_cel
str_cel=[{'Célula';num2str(i)}];
cont=[cont;str_cel];
strs_UV(1:2*num_cel,1)=str_uv;
end

aux(1:num_cel,1)={'Célula '};
aux_1(1:num_cel,1)=1:1:num_cel;
aux_2=num2str(aux_1);
strs_cel=strcat(aux,aux_2);

%cabeçalho
mensagem=improved_xlswrite([caminho '\' nome],{'ESTATÍSTICAS'},...
    'Estatísticas','A1');

mensagem=improved_xlswrite([caminho '\' nome],{'Equipamento'},...
    'Estatísticas','A3');
mensagem=improved_xlswrite([caminho '\' nome],{'Modelo'},...
    'Estatísticas','A4');
mensagem=improved_xlswrite([caminho '\' nome],{'Head ID'},...
    'Estatísticas','A5');
mensagem=improved_xlswrite([caminho '\' nome],{'Frequência de aquisição'},...
    'Estatísticas','A6');
mensagem=improved_xlswrite([caminho '\' nome],{'Intervalo de medição'},...
    'Estatísticas','A7');
mensagem=improved_xlswrite([caminho '\' nome],{'Número de células'},...
    'Estatísticas','A8');
mensagem=improved_xlswrite([caminho '\' nome],{'Profundidade (m)'},...
    'Estatísticas','A9');
mensagem=improved_xlswrite([caminho '\' nome],{'Data Inicial'},...
    'Estatísticas','A10');
mensagem=improved_xlswrite([caminho '\' nome],{'Data final'},...
    'Estatísticas','A11');

%cabeçalho dos resultados

mensagem=improved_xlswrite([caminho '\' nome],{'Valor máximo de corrente'},...
    'Estatísticas','C14');
mensagem=improved_xlswrite([caminho '\' nome],{'Vetorial - Velocidade'},...
    'Estatísticas','C15');
mensagem=improved_xlswrite([caminho '\' nome],{'Vetorial - Direção'},...
    'Estatísticas','D15');
mensagem=improved_xlswrite([caminho '\' nome],{'U (m/s)'},...
    'Estatísticas','E15');
mensagem=improved_xlswrite([caminho '\' nome],{'V (m/s)'},...
    'Estatísticas','F15');
mensagem=improved_xlswrite([caminho '\' nome],{'Valor mínimo de corrente'},...
    'Estatísticas','G14');
mensagem=improved_xlswrite([caminho '\' nome],{'U (m/s)'},...
    'Estatísticas','G15');
mensagem=improved_xlswrite([caminho '\' nome],{'V (m/s)'},...
    'Estatísticas','H15');
mensagem=improved_xlswrite([caminho '\' nome],{'Média'},...
    'Estatísticas','I14');
mensagem=improved_xlswrite([caminho '\' nome],{'Desvio Padrão'},...
    'Estatísticas','M14');
mensagem=improved_xlswrite([caminho '\' nome],{'Mediana'},...
    'Estatísticas','K14');
mensagem=improved_xlswrite([caminho '\' nome],{'Média vetorial'},...
    'Estatísticas','O14');

%resultados

mensagem=improved_xlswrite([caminho '\' nome],max_vet',...
    'Estatísticas','C16');
mensagem=improved_xlswrite([caminho '\' nome],pos_dir_vet,...
    'Estatísticas','D16');
mensagem=improved_xlswrite([caminho '\' nome],max_u',...
    'Estatísticas','E16');
mensagem=improved_xlswrite([caminho '\' nome],max_v',...
    'Estatísticas','F16');
mensagem=improved_xlswrite([caminho '\' nome],min_u',...
    'Estatísticas','G16');
mensagem=improved_xlswrite([caminho '\' nome],min_v',...
    'Estatísticas','H16');
mensagem=improved_xlswrite([caminho '\' nome],media_u',...
    'Estatísticas','I16');
mensagem=improved_xlswrite([caminho '\' nome],media_v',...
    'Estatísticas','J16');
mensagem=improved_xlswrite([caminho '\' nome],mediana_u',...
    'Estatísticas','K16');
mensagem=improved_xlswrite([caminho '\' nome],mediana_v',...
    'Estatísticas','L16');
mensagem=improved_xlswrite([caminho '\' nome],std_u',...
    'Estatísticas','M16');
mensagem=improved_xlswrite([caminho '\' nome],std_v',...
    'Estatísticas','N16');
mensagem=improved_xlswrite([caminho '\' nome],media_vetorial',...
    'Estatísticas','O16');

esc_uv=[repmat({'U(m/s)' 'V(m/s)'},1,3)];
mensagem=improved_xlswrite([caminho '\' nome],esc_uv,'Estatísticas','I15');

%Estatísticas de erros - nomes

mensagem=improved_xlswrite([caminho '\' nome],{'Dados excluídos antes e depois do fundeio'},...
    'Estatísticas','P15');
mensagem=improved_xlswrite([caminho '\' nome],{'Dados resgatados'},...
    'Estatísticas','Q15');
mensagem=improved_xlswrite([caminho '\' nome],{'Fora da faixa ambiental'},...
    'Estatísticas','R15');
mensagem=improved_xlswrite([caminho '\' nome],{'Fora do range do sensor'},...
    'Estatísticas','S15');
mensagem=improved_xlswrite([caminho '\' nome],{'Gaps'},...
    'Estatísticas','T15');
mensagem=improved_xlswrite([caminho '\' nome],{'Repetidos'},...
    'Estatísticas','U15');
mensagem=improved_xlswrite([caminho '\' nome],{'Spikes'},...
    'Estatísticas','V15');
mensagem=improved_xlswrite([caminho '\' nome],{'Gradiente vertical'},...
    'Estatísticas','W15');
mensagem=improved_xlswrite([caminho '\' nome],{'Inclinação'},...
    'Estatísticas','X15');
mensagem=improved_xlswrite([caminho '\' nome],{'Total eliminados'},...
    'Estatísticas','Y15');
mensagem=improved_xlswrite([caminho '\' nome],{'Dados válidos'},...
    'Estatísticas','Z15');
mensagem=improved_xlswrite([caminho '\' nome],{'Taxa de recuperação (%)'},...
    'Estatísticas','AA15');

mensagem=improved_xlswrite([caminho '\' nome],strs_cel,...
    'Estatísticas','B16');

%Estatísticas de erros - valores
tabela_resgatados=[repmat(size(velocidade,1),num_cel,1);(length(velocidade))*num_cel];
tabela_descartados=[sum([range' gaps' rep' spike' amb'],2);sum(sum([range' gaps',...
    rep' spike' amb'],2))];
mensagem=improved_xlswrite([caminho '\' nome],[repmat(excluidos,num_cel,1);excluidos*num_cel],...
    'Estatísticas','P16');
mensagem=improved_xlswrite([caminho '\' nome],tabela_resgatados,...
    'Estatísticas','Q16');
mensagem=improved_xlswrite([caminho '\' nome],[amb';sum(amb)],...
    'Estatísticas','R16');
mensagem=improved_xlswrite([caminho '\' nome],[repmat(0,num_cel,1);0],...
    'Estatísticas','S16');
mensagem=improved_xlswrite([caminho '\' nome],[gaps';sum(gaps)],...
    'Estatísticas','T16');
mensagem=improved_xlswrite([caminho '\' nome],[rep';sum(rep)],...
    'Estatísticas','U16');
mensagem=improved_xlswrite([caminho '\' nome],[spike';sum(spike)],...
    'Estatísticas','V16');
mensagem=improved_xlswrite([caminho '\' nome],[repmat(0,num_cel,1);0],...
    'Estatísticas','W16');
mensagem=improved_xlswrite([caminho '\' nome],[inc';sum(inc)],...
    'Estatísticas','X16');
mensagem=improved_xlswrite([caminho '\' nome],tabela_descartados,'Estatísticas','Y16');
mensagem=improved_xlswrite([caminho '\' nome],tabela_resgatados-tabela_descartados,...
    'Estatísticas','Z16');
mensagem=improved_xlswrite([caminho '\' nome],((tabela_resgatados-tabela_descartados)./tabela_resgatados).*100,...
    'Estatísticas','AA16');
end