function gravar_excel_estat(nome,tempo,velocidade,direcao,caminho,...
    range,gaps,rep,spike,excluidos,inclinacao)
velocidade(velocidade==999)=nan;direcao(direcao==999)=nan;
[u,v]=veldir2uv(velocidade,direcao);
num_cel=size(velocidade,2);

%máximo vetorial
[max_vet e]=nanmax(velocidade);
for i=1:num_cel
    pos_dir_vet(i,1)=direcao(e(i),i);
    pos_tempo_vet(i,1)=tempo(e(i),1);
end

%máximo u, máximo v, mínimo u, mínimo v
[max_u f]=nanmax(u);
for j=1:num_cel
pos_tempo_max_u(j,1)=tempo(f(j),1);
end

[max_v g]=nanmax(v);
for k=1:num_cel
pos_tempo_max_v(k,1)=tempo(g(k),1);
end

[min_u h]=nanmin(u);
for l=1:num_cel
pos_tempo_min_u(l,1)=tempo(h(l),1);
end

[min_v m]=nanmin(v);
for n=1:num_cel
pos_tempo_min_v(n,1)=tempo(m(n),1);
end

%média, mediana e desvio padrão
media_u=nanmean(u);media_v=nanmean(v);
mediana_u=nanmedian(u);mediana_v=nanmedian(v);
std_u=nanstd(u);std_v=nanstd(v);

media_vetorial=[];
for k=1:num_cel
    for kk=1:length(u)
    media_vetorial_aux(kk,k)=sqrt((u(kk,k)^2)+(v(kk,k)^2));
    end
    media_vetorial(1,k)=nanmean(media_vetorial_aux(:,k));
end

str_uv=repmat({'U(m/s)' 'V(m/s)'},1,num_cel);

cont=[];
for i=1:num_cel
str_cel=[{'Célula';num2str(i)}];
cont=[cont;str_cel];
strs_UV(1:2*num_cel,1)=str_uv;
end

aux(1:num_cel,1)={'Célula '};
aux_1(1:num_cel,1)=1:1:num_cel;
aux_2=num2str(aux_1);
strs_cel=strcat(aux,aux_2);

%cabeçalho
mensagem=improved_xlswrite([caminho '\' nome],{'ESTATÍSTICAS'},...
    'Estatísticas','A1');

mensagem=improved_xlswrite([caminho '\' nome],{'Equipamento'},...
    'Estatísticas','A3');
mensagem=improved_xlswrite([caminho '\' nome],{'Modelo'},...
    'Estatísticas','A4');
mensagem=improved_xlswrite([caminho '\' nome],{'Head ID'},...
    'Estatísticas','A5');
mensagem=improved_xlswrite([caminho '\' nome],{'Taxa de aquisição (Hz)'},...
    'Estatísticas','A6');
mensagem=improved_xlswrite([caminho '\' nome],{'Intervalo entre amostragens (s)'},...
    'Estatísticas','A7');
mensagem=improved_xlswrite([caminho '\' nome],{'Período de amostragem (s)'},...
    'Estatísticas','A8');
mensagem=improved_xlswrite([caminho '\' nome],{'Profundidade (m)'},...
    'Estatísticas','A9');
mensagem=improved_xlswrite([caminho '\' nome],{'Data Inicial'},...
    'Estatísticas','A10');
mensagem=improved_xlswrite([caminho '\' nome],{'Data final'},...
    'Estatísticas','A11');

mensagem=improved_xlswrite([caminho '\' nome],{'Correntógrafo'},...
    'Estatísticas','B3');
mensagem=improved_xlswrite([caminho '\' nome],{'Aquadopp Nortek'},...
    'Estatísticas','B4');
mensagem=improved_xlswrite([caminho '\' nome],{'0,92'},...
    'Estatísticas','B6');
mensagem=improved_xlswrite([caminho '\' nome],{'1800'},...
    'Estatísticas','B7');
mensagem=improved_xlswrite([caminho '\' nome],{'300'},...
    'Estatísticas','B8');
mensagem=improved_xlswrite([caminho '\' nome],tempo(1)-693960,...
    'Estatísticas','B10');
mensagem=improved_xlswrite([caminho '\' nome],tempo(end)-693960,...
    'Estatísticas','B11');

%cabeçalho dos resultados

mensagem=improved_xlswrite([caminho '\' nome],{'Valor máximo de corrente'},...
    'Estatísticas','C13');
mensagem=improved_xlswrite([caminho '\' nome],{'Vetorial - Velocidade (m/s)'},...
    'Estatísticas','C14');
mensagem=improved_xlswrite([caminho '\' nome],{'Vetorial - Direção (°)'},...
    'Estatísticas','D14');

mensagem=improved_xlswrite([caminho '\' nome],{'U (m/s)'},...
    'Estatísticas','E14');

mensagem=improved_xlswrite([caminho '\' nome],{'V (m/s)'},...
    'Estatísticas','F14');

mensagem=improved_xlswrite([caminho '\' nome],{'Valor mínimo de corrente'},...
    'Estatísticas','G13');
mensagem=improved_xlswrite([caminho '\' nome],{'U (m/s)'},...
    'Estatísticas','G14');

mensagem=improved_xlswrite([caminho '\' nome],{'V (m/s)'},...
    'Estatísticas','H14');

mensagem=improved_xlswrite([caminho '\' nome],{'Média'},...
    'Estatísticas','I13');
mensagem=improved_xlswrite([caminho '\' nome],{'Desvio Padrão'},...
    'Estatísticas','M13');
mensagem=improved_xlswrite([caminho '\' nome],{'Mediana'},...
    'Estatísticas','K13');
mensagem=improved_xlswrite([caminho '\' nome],{'Média vetorial (m/s)'},...
    'Estatísticas','O13');

%resultados

mensagem=improved_xlswrite([caminho '\' nome],max_vet',...
    'Estatísticas','C15');
mensagem=improved_xlswrite([caminho '\' nome],pos_dir_vet,...
    'Estatísticas','D15');
% mensagem=improved_xlswrite([caminho '\' nome],pos_tempo_vet-693960,...
%     'Estatísticas','E16');
mensagem=improved_xlswrite([caminho '\' nome],max_u',...
    'Estatísticas','E15');
% mensagem=improved_xlswrite([caminho '\' nome],pos_tempo_max_u-693960,...
%     'Estatísticas','G16');
mensagem=improved_xlswrite([caminho '\' nome],max_v',...
    'Estatísticas','F15');
% mensagem=improved_xlswrite([caminho '\' nome],pos_tempo_max_v-693960,...
%     'Estatísticas','I16');
mensagem=improved_xlswrite([caminho '\' nome],min_u',...
    'Estatísticas','G15');
% mensagem=improved_xlswrite([caminho '\' nome],pos_tempo_min_u-693960,...
%     'Estatísticas','K16');
mensagem=improved_xlswrite([caminho '\' nome],min_v',...
    'Estatísticas','H15');
% mensagem=improved_xlswrite([caminho '\' nome],pos_tempo_min_v-693960,...
%     'Estatísticas','M16');
mensagem=improved_xlswrite([caminho '\' nome],media_u',...
    'Estatísticas','I15');
mensagem=improved_xlswrite([caminho '\' nome],media_v',...
    'Estatísticas','J15');
mensagem=improved_xlswrite([caminho '\' nome],mediana_u',...
    'Estatísticas','K15');
mensagem=improved_xlswrite([caminho '\' nome],mediana_v',...
    'Estatísticas','L15');
mensagem=improved_xlswrite([caminho '\' nome],std_u',...
    'Estatísticas','M15');
mensagem=improved_xlswrite([caminho '\' nome],std_v',...
    'Estatísticas','N15');
mensagem=improved_xlswrite([caminho '\' nome],media_vetorial',...
    'Estatísticas','O15');

esc_uv=[repmat({'U(m/s)' 'V(m/s)'},1,3)];
mensagem=improved_xlswrite([caminho '\' nome],esc_uv,'Estatísticas','I14');

%Estatísticas de erros - nomes

mensagem=improved_xlswrite([caminho '\' nome],{'Dados excluídos antes e depois do fundeio'},...
    'Estatísticas','P13');
mensagem=improved_xlswrite([caminho '\' nome],{'Dados resgatados'},...
    'Estatísticas','Q13');
mensagem=improved_xlswrite([caminho '\' nome],{'Fora da faixa ambiental'},...
    'Estatísticas','R13');
mensagem=improved_xlswrite([caminho '\' nome],{'Fora do range do sensor'},...
    'Estatísticas','S13');
mensagem=improved_xlswrite([caminho '\' nome],{'Gaps'},...
    'Estatísticas','T13');
mensagem=improved_xlswrite([caminho '\' nome],{'Repetidos'},...
    'Estatísticas','U13');
mensagem=improved_xlswrite([caminho '\' nome],{'Spikes'},...
    'Estatísticas','V13');
mensagem=improved_xlswrite([caminho '\' nome],{'Gradiente vertical'},...
    'Estatísticas','W13');
mensagem=improved_xlswrite([caminho '\' nome],{'Inclinação'},...
    'Estatísticas','X13');
mensagem=improved_xlswrite([caminho '\' nome],{'Total eliminados'},...
    'Estatísticas','Y13');
mensagem=improved_xlswrite([caminho '\' nome],{'Dados válidos'},...
    'Estatísticas','Z13');
mensagem=improved_xlswrite([caminho '\' nome],{'Taxa de recuperação (%)'},...
    'Estatísticas','AA13');

mensagem=improved_xlswrite([caminho '\' nome],strs_cel,...
    'Estatísticas','B15');

%Estatísticas de erros - valores
tabela_resgatados=[repmat(size(velocidade,1),num_cel,1)];
tabela_descartados=[sum([range' gaps' rep' spike' inclinacao],2)];
mensagem=improved_xlswrite([caminho '\' nome],[repmat(excluidos,num_cel,1)],...
    'Estatísticas','P15');
mensagem=improved_xlswrite([caminho '\' nome],tabela_resgatados,...
    'Estatísticas','Q15');
mensagem=improved_xlswrite([caminho '\' nome],[repmat(0,num_cel,1)],...
    'Estatísticas','R15');
mensagem=improved_xlswrite([caminho '\' nome],[range],...
    'Estatísticas','S15');
mensagem=improved_xlswrite([caminho '\' nome],[gaps],...
    'Estatísticas','T15');
mensagem=improved_xlswrite([caminho '\' nome],[rep],...
    'Estatísticas','U15');
mensagem=improved_xlswrite([caminho '\' nome],[spike],...
    'Estatísticas','V15');
mensagem=improved_xlswrite([caminho '\' nome],[repmat(0,num_cel,1)],'Estatísticas','W15');
mensagem=improved_xlswrite([caminho '\' nome],inclinacao,'Estatísticas','X15');
mensagem=improved_xlswrite([caminho '\' nome],tabela_descartados,'Estatísticas','Y15');
mensagem=improved_xlswrite([caminho '\' nome],tabela_resgatados-tabela_descartados,...
    'Estatísticas','Z15');
mensagem=improved_xlswrite([caminho '\' nome],((tabela_resgatados-tabela_descartados)./tabela_resgatados).*100,...
    'Estatísticas','AA15');
end