function gravar_excel_onda(nome,tempo,matriz,caminho,num_rep,...
    num_gap,num_sinc,num_amb,num_tilt,dados_excluidos,percent_good)
%%
mensagem=improved_xlswrite([caminho '\' nome],{'DADOS PROCESSADOS DE ONDA'},...
    'Ondas','A1');

mensagem=improved_xlswrite([caminho '\' nome],{'Equipamento'},...
    'Ondas','A3');
mensagem=improved_xlswrite([caminho '\' nome],{'Modelo'},...
    'Ondas','A4');
mensagem=improved_xlswrite([caminho '\' nome],{'Head ID'},...
    'Ondas','A5');
mensagem=improved_xlswrite([caminho '\' nome],{'Frequência de aquisição'},...
    'Ondas','A6');
mensagem=improved_xlswrite([caminho '\' nome],{'Intervalo de medição'},...
    'Ondas','A7');
mensagem=improved_xlswrite([caminho '\' nome],{'Profundidade (m)'},...
    'Ondas','A8');
mensagem=improved_xlswrite([caminho '\' nome],{'Data Inicial'},...
    'Ondas','A9');
mensagem=improved_xlswrite([caminho '\' nome],{'Data final'},...
    'Ondas','A10');
mensagem=improved_xlswrite([caminho '\' nome],{'Tempo de coleta'},...
    'Ondas','A11');
mensagem=improved_xlswrite([caminho '\' nome],tempo(end)-tempo(1),...
    'Ondas','B11');
mensagem=improved_xlswrite([caminho '\' nome],{'dias'},...
    'Ondas','C11');

mensagem=improved_xlswrite([caminho '\' nome],{'Data'},...
    'Ondas','A13');
mensagem=improved_xlswrite([caminho '\' nome],{'Hm0 (m)'},...
    'Ondas','B13');
mensagem=improved_xlswrite([caminho '\' nome],{'H10 (m)'},...
    'Ondas','C13');
mensagem=improved_xlswrite([caminho '\' nome],{'Hmax (m)'},...
    'Ondas','D13');
mensagem=improved_xlswrite([caminho '\' nome],{'Hmean (m)'},...
    'Ondas','E13');
mensagem=improved_xlswrite([caminho '\' nome],{'H3 (m)'},...
    'Ondas','F13');
mensagem=improved_xlswrite([caminho '\' nome],{'Tp (s)'},...
    'Ondas','G13');
mensagem=improved_xlswrite([caminho '\' nome],{'Tm02 (s)'},...
    'Ondas','H13');
mensagem=improved_xlswrite([caminho '\' nome],{'Tz (s)'},...
    'Ondas','I13');
mensagem=improved_xlswrite([caminho '\' nome],{'DirTp (°)'},...
    'Ondas','J13');
mensagem=improved_xlswrite([caminho '\' nome],{'SprTp (°)'},...
    'Ondas','K13');
mensagem=improved_xlswrite([caminho '\' nome],{'MeanDir (°)'},...
    'Ondas','L13');

mensagem=improved_xlswrite([caminho '\' nome],{'ESTATÍSTICAS DE ONDAS'},...
    'Ondas','N2');
mensagem=improved_xlswrite([caminho '\' nome],{'Maior altura'},...
    'Ondas','N3');
mensagem=improved_xlswrite([caminho '\' nome],{'Menor altura'},...
    'Ondas','N4');
mensagem=improved_xlswrite([caminho '\' nome],{'Maior período'},...
    'Ondas','N5');
mensagem=improved_xlswrite([caminho '\' nome],{'Menor período'},...
    'Ondas','N6');
mensagem=improved_xlswrite([caminho '\' nome],{'Maior direção'},...
    'Ondas','N7');
mensagem=improved_xlswrite([caminho '\' nome],{'Menor direção'},...
    'Ondas','N8');
mensagem=improved_xlswrite([caminho '\' nome],{'Amplitude direcional'},...
    'Ondas','N9');

mensagem=improved_xlswrite([caminho '\' nome],{'Dados excluídos antes e depois do fundeio'},...
    'Ondas','N11');
mensagem=improved_xlswrite([caminho '\' nome],{'Dados resgatados'},...
    'Ondas','N12');
mensagem=improved_xlswrite([caminho '\' nome],{'Fora da faixa ambiental'},...
    'Ondas','N13');
mensagem=improved_xlswrite([caminho '\' nome],{'Fora do range'},...
    'Ondas','N14');
mensagem=improved_xlswrite([caminho '\' nome],{'Gaps'},...
    'Ondas','N15');
mensagem=improved_xlswrite([caminho '\' nome],{'Repetidos'},...
    'Ondas','N16');
mensagem=improved_xlswrite([caminho '\' nome],{'Spike'},...
    'Ondas','N17');
mensagem=improved_xlswrite([caminho '\' nome],{'Inclinação'},...
    'Ondas','N18');
mensagem=improved_xlswrite([caminho '\' nome],{'Total eliminado'},...
    'Ondas','N19');
mensagem=improved_xlswrite([caminho '\' nome],{'Dados aceitáveis'},...
    'Ondas','N20');
mensagem=improved_xlswrite([caminho '\' nome],{'Taxa de recuperação'},...
    'Ondas','N21');

mensagem=improved_xlswrite([caminho '\' nome],tempo-693960,...
    'Ondas','A14');
% matriz_out2=matriz_out;
% [l_grad]=find(isnan(matriz_out2));
% matriz_out2(l_grad)=999;

mensagem=improved_xlswrite([caminho '\' nome],nanmax(matriz(:,1)),...
    'Ondas','O3');
mensagem=improved_xlswrite([caminho '\' nome],nanmin(matriz(:,1)),...
    'Ondas','O4');
mensagem=improved_xlswrite([caminho '\' nome],nanmax(matriz(:,6)),...
    'Ondas','O5');
mensagem=improved_xlswrite([caminho '\' nome],nanmin(matriz(:,6)),...
    'Ondas','O6');
ensagem=improved_xlswrite([caminho '\' nome],nanmax(matriz(:,11)),...
    'Ondas','O7');
mensagem=improved_xlswrite([caminho '\' nome],nanmin(matriz(:,11)),...
    'Ondas','O8');
mensagem=improved_xlswrite([caminho '\' nome],nanmax(matriz(:,11))-nanmin(matriz(:,11)),...
    'Ondas','O9');

mensagem=improved_xlswrite([caminho '\' nome],dados_excluidos,...
    'Ondas','O11');
mensagem=improved_xlswrite([caminho '\' nome],size(tempo,1),...
    'Ondas','O12');
mensagem=improved_xlswrite([caminho '\' nome],num_amb,...
    'Ondas','O13');
mensagem=improved_xlswrite([caminho '\' nome],0,...
    'Ondas','O14');
mensagem=improved_xlswrite([caminho '\' nome],num_gap,...
    'Ondas','O15');
mensagem=improved_xlswrite([caminho '\' nome],num_rep,...
    'Ondas','O16');
mensagem=improved_xlswrite([caminho '\' nome],0,...
    'Ondas','O17');
mensagem=improved_xlswrite([caminho '\' nome],num_tilt,...
    'Ondas','O18');
mensagem=improved_xlswrite([caminho '\' nome],num_gap+num_rep+num_sinc+num_tilt+num_amb,...
    'Ondas','O19');
mensagem=improved_xlswrite([caminho '\' nome],size(tempo,1)-(num_gap+num_rep+num_sinc+num_tilt+num_amb),...
    'Ondas','O20');
mensagem=improved_xlswrite([caminho '\' nome],((size(tempo,1)-(num_gap+num_rep+num_sinc+num_tilt+num_amb))/size(tempo,1))*100,...
    'Ondas','O21');

[ind]=find(isnan(matriz));
matriz(ind)=999;
mensagem=improved_xlswrite([caminho '\' nome],matriz,...
    'Ondas','B14');
xls_delete_sheets([nome '.xls'],{'Plan1';'Plan2';'Plan3'})

end